[package]
name = "opensmtpd-filter-gglgrp"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"
license = "GPL-3.0"
authors = ["Alexander A. Klimov <a@kli.mov>"]

[dependencies]
itertools = "0.14.0"
mail-parser = "0.11.0"
